// Simulamos una base de datos con listas de estudiantes
const estudiantes = [
  {
    id: 1,
    nombre: "Juan Pérez",
    edad: 20,
    email: "juan.perez@email.com",
    carrera: "Ingeniería Informática",
    semestre: 4,
    estado: "activo",
    fechaCreacion: "2024-01-15",
  },
  {
    id: 2,
    nombre: "Ana Gómez",
    edad: 22,
    email: "ana.gomez@email.com",
    carrera: "Desarrollo de Software",
    semestre: 6,
    estado: "activo",
    fechaCreacion: "2024-01-10",
  },
  {
    id: 3,
    nombre: "Carlos Rodríguez",
    edad: 19,
    email: "carlos.rodriguez@email.com",
    carrera: "Ingeniería Informática",
    semestre: 2,
    estado: "activo",
    fechaCreacion: "2024-02-01",
  },
  {
    id: 4,
    nombre: "María López",
    edad: 24,
    email: "maria.lopez@email.com",
    carrera: "Ciencia de Datos",
    semestre: 8,
    estado: "activo",
    fechaCreacion: "2023-12-20",
  },
  {
    id: 5,
    nombre: "Luis Martínez",
    edad: 21,
    email: "luis.martinez@email.com",
    carrera: "Desarrollo de Software",
    semestre: 5,
    estado: "activo",
    fechaCreacion: "2024-01-25",
  },
  {
    id: 6,
    nombre: "Carmen Sánchez",
    edad: 23,
    email: "carmen.sanchez@email.com",
    carrera: "Ingeniería Informática",
    semestre: 7,
    estado: "activo",
    fechaCreacion: "2023-11-15",
  },
  {
    id: 7,
    nombre: "Diego Torres",
    edad: 18,
    email: "diego.torres@email.com",
    carrera: "Desarrollo de Software",
    semestre: 1,
    estado: "activo",
    fechaCreacion: "2024-03-01",
  },
  {
    id: 8,
    nombre: "Sofia Ramírez",
    edad: 25,
    email: "sofia.ramirez@email.com",
    carrera: "Ciencia de Datos",
    semestre: 9,
    estado: "activo",
    fechaCreacion: "2023-10-10",
  },
  {
    id: 9,
    nombre: "Andrés Morales",
    edad: 20,
    email: "andres.morales@email.com",
    carrera: "Ingeniería Informática",
    semestre: 3,
    estado: "activo",
    fechaCreacion: "2024-01-20",
  },
  {
    id: 10,
    nombre: "Valentina Herrera",
    edad: 22,
    email: "valentina.herrera@email.com",
    carrera: "Desarrollo de Software",
    semestre: 6,
    estado: "activo",
    fechaCreacion: "2024-01-05",
  },
  {
    id: 11,
    nombre: "Roberto Silva",
    edad: 26,
    email: "roberto.silva@email.com",
    carrera: "Ciencia de Datos",
    semestre: 10,
    estado: "activo",
    fechaCreacion: "2023-09-15",
  },
  {
    id: 12,
    nombre: "Camila Vargas",
    edad: 19,
    email: "camila.vargas@email.com",
    carrera: "Ingeniería Informática",
    semestre: 2,
    estado: "activo",
    fechaCreacion: "2024-02-15",
  },
  {
    id: 13,
    nombre: "Fernando Castro",
    edad: 23,
    email: "fernando.castro@email.com",
    carrera: "Desarrollo de Software",
    semestre: 7,
    estado: "activo",
    fechaCreacion: "2023-12-05",
  },
  {
    id: 14,
    nombre: "Isabella Mendoza",
    edad: 21,
    email: "isabella.mendoza@email.com",
    carrera: "Ingeniería Informática",
    semestre: 5,
    estado: "activo",
    fechaCreacion: "2024-01-30",
  },
  {
    id: 15,
    nombre: "Miguel Rojas",
    edad: 24,
    email: "miguel.rojas@email.com",
    carrera: "Ciencia de Datos",
    semestre: 8,
    estado: "activo",
    fechaCreacion: "2023-11-20",
  },
  {
    id: 16,
    nombre: "Daniela Jiménez",
    edad: 20,
    email: "daniela.jimenez@email.com",
    carrera: "Desarrollo de Software",
    semestre: 4,
    estado: "activo",
    fechaCreacion: "2024-02-10",
  },
  {
    id: 17,
    nombre: "Alejandro Ruiz",
    edad: 27,
    email: "alejandro.ruiz@email.com",
    carrera: "Ciencia de Datos",
    semestre: 11,
    estado: "activo",
    fechaCreacion: "2023-08-15",
  },
  {
    id: 18,
    nombre: "Natalia Vega",
    edad: 22,
    email: "natalia.vega@email.com",
    carrera: "Ingeniería Informática",
    semestre: 6,
    estado: "activo",
    fechaCreacion: "2024-01-12",
  },
  {
    id: 19,
    nombre: "Gabriel Paredes",
    edad: 19,
    email: "gabriel.paredes@email.com",
    carrera: "Desarrollo de Software",
    semestre: 1,
    estado: "activo",
    fechaCreacion: "2024-03-05",
  },
  {
    id: 20,
    nombre: "Lucía Fuentes",
    edad: 25,
    email: "lucia.fuentes@email.com",
    carrera: "Ciencia de Datos",
    semestre: 9,
    estado: "activo",
    fechaCreacion: "2023-10-25",
  },
  {
    id: 21,
    nombre: "Ricardo Soto",
    edad: 23,
    email: "ricardo.soto@email.com",
    carrera: "Ingeniería Informática",
    semestre: 7,
    estado: "activo",
    fechaCreacion: "2023-12-10",
  },
  {
    id: 22,
    nombre: "Paula Contreras",
    edad: 21,
    email: "paula.contreras@email.com",
    carrera: "Desarrollo de Software",
    semestre: 5,
    estado: "activo",
    fechaCreacion: "2024-01-18",
  },
];

module.exports = estudiantes;
