// Simulamos una base de datos con listas de inscripciones
const inscripciones = [
  {
    id: 1,
    estudianteId: 1,
    cursoId: 1,
    fechaInscripcion: "2024-01-20",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 2,
    estudianteId: 2,
    cursoId: 2,
    fechaInscripcion: "2024-01-15",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 3,
    estudianteId: 3,
    cursoId: 3,
    fechaInscripcion: "2024-02-05",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 4,
    estudianteId: 4,
    cursoId: 21,
    fechaInscripcion: "2024-01-10",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 5,
    estudianteId: 5,
    cursoId: 4,
    fechaInscripcion: "2024-01-25",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 6,
    estudianteId: 6,
    cursoId: 6,
    fechaInscripcion: "2024-01-12",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 7,
    estudianteId: 7,
    cursoId: 8,
    fechaInscripcion: "2024-02-10",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 8,
    estudianteId: 8,
    cursoId: 22,
    fechaInscripcion: "2024-01-08",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 9,
    estudianteId: 9,
    cursoId: 5,
    fechaInscripcion: "2024-01-18",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 10,
    estudianteId: 10,
    cursoId: 7,
    fechaInscripcion: "2024-01-30",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 11,
    estudianteId: 11,
    cursoId: 21,
    fechaInscripcion: "2024-01-06",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 12,
    estudianteId: 12,
    cursoId: 3,
    fechaInscripcion: "2024-02-20",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 13,
    estudianteId: 13,
    cursoId: 10,
    fechaInscripcion: "2024-01-22",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 14,
    estudianteId: 14,
    cursoId: 1,
    fechaInscripcion: "2024-01-19",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 15,
    estudianteId: 15,
    cursoId: 22,
    fechaInscripcion: "2024-01-09",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 16,
    estudianteId: 16,
    cursoId: 4,
    fechaInscripcion: "2024-02-12",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 17,
    estudianteId: 17,
    cursoId: 21,
    fechaInscripcion: "2024-01-07",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 18,
    estudianteId: 18,
    cursoId: 2,
    fechaInscripcion: "2024-01-14",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 19,
    estudianteId: 19,
    cursoId: 3,
    fechaInscripcion: "2024-03-10",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 20,
    estudianteId: 20,
    cursoId: 22,
    fechaInscripcion: "2024-01-11",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 21,
    estudianteId: 21,
    cursoId: 6,
    fechaInscripcion: "2024-01-16",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
  {
    id: 22,
    estudianteId: 22,
    cursoId: 9,
    fechaInscripcion: "2024-01-24",
    estado: "activa",
    calificacion: null,
    fechaCompletado: null,
  },
];

module.exports = inscripciones;
